### List all messages
GET http://localhost:3000/messages

### Get one
GET http://localhost:3000/messages/5

### Create (empty line after content type is necessary!)
POST  http://localhost:3000/messages
content-type: application/json

{
    "content": "hi there"
}

### Create ERROR
POST  http://localhost:3000/messages
content-type: application/json

{
    "content": null
}
